### ISSUE TITLE
Testing a game that transfer lamports: "sum of account balances before and after instruction do not match"

### ISSUE THREAD

**Issue by netpoe** [project-serum/anchor-book#75]
`instructions::play` is defined like this:

```rust
use crate::state::game::*;
use anchor_lang::prelude::*;

pub fn play(ctx: Context<Play>, data: FlipArgs) -> Result<()> {
    let game = &mut ctx.accounts.game;
    game.flip(&ctx.accounts.player, data)
}

#[derive(Accounts)]
pub struct Play<'info> {
    #[account(mut)]
    pub game: Account<'info, Game>,
    #[account(init, payer = payer, space = Game::MAXIMUM_SIZE + 8)]
    /// CHECK: insecure
    pub player: AccountInfo<'info>,
    #[account(mut)]
    pub payer: Signer<'info>,
    pub system_program: Program<'info, System>,
}
```

`game.flip` will then attempt to charge the `player` a fee: 

```rust
pub fn flip(&mut self, player: &AccountInfo, data: FlipArgs) -> Result<()> {
        match self.charge_fee(player) {
            Err(e) => return Err(e),
            _ => match data.heads_or_tails {
                true => self.play_heads(player),
                false => self.play_tails(player),
            },
        }
    }

    fn charge_fee(&self, player: &AccountInfo) -> Result<()> {
        if **player.try_borrow_lamports()? < self.static_amount {
            return Err(CoinflipError::InsufficientFunds.into());
        }

        let fee = self.calculate_fee();

        **player.try_borrow_mut_lamports()? -= fee as u64;

        Ok(())
    }
```

Typescript chai tests try to setup the game, airdrop balance to the player and then `flip`:

```typescript
it("play: heads", async () => {
    const gameKeypair = anchor.web3.Keypair.generate();
    await setupGame(gameKeypair);

    const playerKeypair = anchor.web3.Keypair.generate();
    const signature = await programProvider.connection.requestAirdrop(
      playerKeypair.publicKey,
      anchor.web3.LAMPORTS_PER_SOL,
    );
    await programProvider.connection.confirmTransaction(signature);
    const balance = await programProvider.connection.getBalance(playerKeypair.publicKey);

    console.log(balance);

    await program.methods
      .flip({ headsOrTails: true })
      .accounts({
        game: gameKeypair.publicKey,
        player: playerKeypair.publicKey,
      })
      .signers([playerKeypair])
      .rpc();

    // ...
  });
```

But fails with: 

```
2) solana-anchor-coinflip
       play: heads:
     Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: sum of account balances before and after instruction do not match
      at Connection.sendEncodedTransaction (node_modules/@solana/web3.js/src/connection.ts:4068:13)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at Connection.sendRawTransaction (node_modules/@solana/web3.js/src/connection.ts:4030:20)
      at sendAndConfirmRawTransaction (node_modules/@project-serum/anchor/src/provider.ts:284:21)
      at AnchorProvider.sendAndConfirm (node_modules/@project-serum/anchor/src/provider.ts:144:14)
      at MethodsBuilder.rpc [as _rpcFn] (node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:29:16)
```

I think the problem lies in the `pub struct Play` definition: 

```rust
#[derive(Accounts)]
pub struct Play<'info> {
    #[account(mut)]
    pub game: Account<'info, Game>,
    #[account(init, payer = payer, space = Game::MAXIMUM_SIZE + 8)]
    /// CHECK: insecure
    pub player: AccountInfo<'info>,
    #[account(mut)]
    pub payer: Signer<'info>,
    pub system_program: Program<'info, System>,
}
```

**Comment by netpoe** [comment]
@paul-schaaf @kennethcassel @sohrab-  would appreciate your help here as the TicTacToe example does not include payments or lamport transfers. 

cc @susguzman @ktoxcon

**Comment by paul-schaaf** [comment]
pls go to discord for support questions like this
